root = "."
testdata_dir = "testdata"
tmp_dir = "air"

[build]
  args_bin = []
  cmd = "go test ./... && go build -gcflags=\"all=-N -l\" -o ./air/main_comp -buildvcs=false ."
  bin = "./air/main"
  delay = 1
  exclude_dir = ["assets", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = true
  full_bin = ""
  include_dir = ["pkg"]
  include_ext = ["go", "tpl", "tmpl", "html","mod","sum"]
  include_file = []
  kill_delay = 500
  log = "air.log"
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = true
  poll = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  app_port = 0
  enabled = false
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
